language: node_js
node_js:
- 10
deploy:
  provider: npm
  email: levonet@gmail.com
  api_key:
    secure: nR1P7lc/Fs/rvNba7bJ5Y3sMPqLdxQbS9vxw9eFKtWtV/EgxYX4S/sPZ+awEMJZ7x9CK+Z5LcQ+7geGKkQZ+u9LrWbCML5D+/GTzQ3ni/b78pRUop4grZdcKEjYnLbYFWpv3fkXOqUbu9exDjwrZMYfWpxONP2DS/DKEJbYqIzc5sicjF3nuCuxqx3OMWA3FqjpKGK3R29Bl7Pi9/WacLC6AYbS+NhgiBodV9YaWn/QbEZ6ibn4E+g9NiEL8qTrSLABfL/SRXjrVy4+ZthNazs2QJwGPE8S+X+hIazQ5RvmUY0kZPflXd1+6w2SUi7BeGejkln9vCebOqCAQv3LyCrWADoK1NLbSTFEZpJZGhB8Fsi74JZNhg53e5LsoiXfvKowa1xL4xtFMVkSkoThXWaBlHDMtDuoTAQn5LIYO/67xwA9DLkVkkQF2ZSsL1NRf164L2vxifvK9QCaVcicLeEuHZvxQPZ8+ShBKqjR/DEvpNWhx10TZ1xiKry1KJiansoGcEQjbec68oiBbHX+lNIFHm8m28IzzdECcTb8OAkf2owIEK9DIQe46Xihiec4P4Lvq52xHkWYs1Oex1iF4n0n4m3okfOyOQZGaAcM9uVFeMm3ziXDiYwUzegRStg/LUE6F/T2Px0ACVq6qAE6WY3bUXYgytVcx3007hHwY9Bk=
  on:
    tags: true
    repo: swaggerql/swagger-combine-ui
